#!/usr/bin/env bash

# clone repo
_path_repo="$HOME/work/clsa-vpn"
if ! [ -d "$_path_repo" ]; then
	mkdir -p "$(dirname "$_path_repo")"
	cd "$(dirname "$_path_repo")" || exit
	git clone https@github.com:dycw/clsa-vpn.git
else
	cd "$_path_repo" || exit
	git pull
fi

# SSH key
if [[ "$(uname -s)" =~ Linux* ]] && ! [ -f "$HOME/.ssh/id_rsa" ]; then
	echo "$(date '+%Y-%m-%d %H:%M:%S'): Generating SSH key..."
	echo 'Generating SSH key...'
	ssh-keygen -q -t rsa -N '' <<<$'\ny' >/dev/null 2>&1
	# https://stackoverflow.com/a/43235320
	sudo apt install -y xclip
	xclip -sel clipboard <"$HOME/.ssh/id_rsa.pub"
	xdg-open https://github.com/settings/ssh/new
	read -p "Press 'y' to continue... " -n 1 -r
	echo
	if ! [[ "$REPLY" =~ ^[Yy]$ ]]; then
		echo "$(date '+%Y-%m-%d %H:%M:%S'): Exiting..."
		exit 0
	fi
fi

# client
_version=4.10.03104
if [[ "$(uname -s)" =~ Darwin* ]]; then
	installer f"anyconnect-macos-${_version}-core-vpn-webdeploy-k9.pkg"
elif [[ "$(uname -s)" =~ Linux* ]]; then
	# anyconnect
	_anyconnect_linux_ver="anyconnect-linux64-${_version}"
	_anyconnect_tar="${_anyconnect_linux_ver}-predeploy-k9.tar.gz"
	_tmp_dir=$(mktemp -d -t clsa-vpn-"$(date +%Y%m%d%H%M%S)"-XXXXXXXXXX)
	cd "$_tmp_dir" || exit
	cp "${_path_repo}/${_anyconnect_tar}" .
	tar zxvf "$_anyconnect_tar"
	cd "${_anyconnect_linux_ver}/vpn" || exit
	yes | sudo './vpn_install.sh'
	cd "$_path_repo" || exit
	rm -rf "$_tmp_dir"

	# vpnui
	sudo apt -y install libcanberra-gtk-module

	# remmina
	if ! [ -x "$(command -v remmina)" ]; then
		sudo apt -y install remmina-plugin-rdp
	fi
fi
